dist: bionic
language: R
warnings_are_errors: true

sudo: required

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y -q libopenmpi-dev openmpi-bin
  - LD_PRELOAD=/usr/lib/openmpi/lib/libmpi.so
  - R -e "install.packages('crlapply', repos='https://hpcran.org')"
