dist: bionic
language: R
warnings_are_errors: true

apt_packages:
  - ssh
  - libopenmpi-dev
  - openmpi-bin

before_install:
  - LD_PRELOAD=/usr/lib/openmpi/lib/libmpi.so
  - R -e "install.packages('crlapply', repos='https://hpcran.org')"
