dist: trusty
sudo: required
language: R
warnings_are_errors: true

env:
  - _R_CHECK_CRAN_INCOMING_=false

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y -q libopenmpi-dev openmpi-bin libopenblas-dev
  - LD_PRELOAD=/usr/lib/openmpi/lib/libmpi.so
  - ln -s /usr/lib/x86_64-linux-gnu/libopenblas.so /usr/lib/R/libRblas.so
  - ln -s /usr/lib/x86_64-linux-gnu/libopenblas.so /usr/lib/R/libRlapack.so
  - R -e "install.packages('crlapply', repos='https://hpcran.org')"
  - Rscript -e "install.packages('pbdMPI', repos = 'https://cran.r-project.org/')"
