os: linux
dist: trusty
language: r
warnings_are_errors: true

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y -q libopenmpi-dev openmpi-bin
  - LD_PRELOAD=/usr/lib/openmpi/lib/libmpi.so
  - R -e "install.packages('crlapply', repos='https://hpcran.org')"
  - Rscript -e "install.packages('pbdMPI', repos = 'https://cran.r-project.org/')"
